### PR TITLE
Fixes naming, new data structures

### LINKED ISSUE #29: Improve variable names and naming consistency

### PR DESCRIPTION
**Pull request by lovesegfault**
Fixes #29

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -11,28 +11,214 @@ use rand::Rng;
...
+
+impl Grid {
+    fn new(b: Option<(usize, usize)>) -> Self {
+        match b {
+            None => Grid {
+                grid: CellSet::new(),
+                bounds: b,
+            },
+            _ => Grid {
+                grid: CellSet::with_capacity(b.unwrap().0 * b.unwrap().1),
```
Comment (maffoo) [inline src/lib.rs]: Can unpack the tuple in the match case, e.g.
```rust
match b {
    None => ...,
    Some((w, h)) => Grid {
        grid: CellSet::with_capacity(w * h),
        bounds: b,
    }
```

File: src/lib.rs [hunk 2]
```diff
@@ -11,28 +11,214 @@ use rand::Rng;
...
+                bounds: b,
+            },
+        }
+
+    }
+    fn insert(&mut self, cell: Cell) {
+        if self.bounds != None {
```
Comment (maffoo) [inline src/lib.rs]: Would be more idiomatic to do `match self.bounds` here, especially since you can deconstruct the bounds tuple instead of using `unwrap()`, as suggested above.

File: src/lib.rs [hunk 3]
```diff
@@ -11,28 +11,214 @@ use rand::Rng;
...
+        } else {
+            self.grid.insert(cell);
+        }
+    }
+    fn contains(&self, cell: &Cell) -> bool {
+        self.grid.contains(cell)
+    }
+
+    fn x_bound(&self) -> usize {
+        self.bounds.unwrap().0
```
Comment (maffoo) [inline src/lib.rs]: Rather than `unwrap`ping here, should probably return `Option<usize>`. Generally speaking, `unwrap` is a code smell.

File: src/lib.rs [hunk 4]
```diff
@@ -11,28 +11,214 @@ use rand::Rng;
...
+        self.bounds.unwrap().1
+    }
+
+    pub fn gen(&mut self) {
+        if self.bounds == None {
+            return;
+        }
+        self.grid.clear();
+        for x in 0..self.bounds.unwrap().0 {
+            for y in 0..self.bounds.unwrap().1 {
```
Comment (maffoo) [inline src/lib.rs]: Here, too, should use a match statement instead of `unwrap`

File: src/lib.rs [hunk 5]
```diff
@@ -11,28 +11,214 @@ use rand::Rng;
...
+    /// # Example
+    ///
+    /// ```
+    /// # #[macro_use] extern crate hemoglobin; fn main(){
+    ///
+    /// let grid = hemoglobin::Grid::from(ovec!["#  ", "   ", " # "]);
+    /// # }
+    /// ```
+    fn from(s: Vec<String>) -> Self {
+        let mut result = Grid::new(None);
```
Comment (maffoo) [inline src/lib.rs]: Seems like you might want to infer bounds based on the number of strings in `s`, and the length of the strings. What is the use case for a `Grid` without bounds?

File: src/lib.rs [hunk 6]
```diff
@@ -11,28 +11,214 @@ use rand::Rng;
...
+                    result.insert((x, y));
+                }
+            }
+        }
+        result
+    }
+}
+
+pub struct Rule {
+    dec: BigInt,
```
Comment (maffoo) [inline src/lib.rs]: It might be better to use `UBigInt` instead, since there's no need for a sign bit to describe rules.

File: src/lib.rs [hunk 7]
```diff
@@ -11,28 +11,214 @@ use rand::Rng;
...
+        }
+    }
+
+    fn decide_next_state(&self, cell: &Cell) -> bool {
+        let state = get_state(&self.grid, cell);
+        self.rule.bin[state]
+    }
+
+    pub fn step(&mut self) {
+        let mut new_state = Grid::new(self.grid.bounds);
```
Comment (maffoo) [inline src/lib.rs]: I think it would be better not to allocate a new grid at each step, but rather to preallocate two grids and "double-buffer" between them. (This probably doesn't make much difference in the case where a grid uses a hashtable, but if the grid state were represented by a `Vec<BitVec>` instead, or something like that, then having a double buffer would mean there's no need to allocate memory at each step.

File: src/lib.rs [hunk 8]
```diff
@@ -11,28 +11,214 @@ use rand::Rng;
...
+                for i in 0..result_reversed.len() {
+                    result.set(i, result_reversed[result_reversed.len() - i - 1]);
+                }
+                result
+            },
+        }
+    }
+}
+
+impl From<String> for Rule {
```
Comment (maffoo) [inline src/lib.rs:131]: Might want to make this `From<&str>` instead so it will work for static strings without having to convert to `String` and allocate memory. (Should still be able to use `String`s because they coerce to `&str` with `&`.)

File: src/lib.rs [hunk 9]
```diff
@@ -11,28 +11,214 @@ use rand::Rng;
...
+    fn from(s: String) -> Self {
+        Rule::from(s.parse::<BigInt>().unwrap())
```
Comment (maffoo) [inline src/lib.rs]: Having `unwrap` in a conversion like this seems bad since it might panic. Should probably implement a conversion to a `Result` type that could be an error instead (like parsing to `BigInt` itself).

File: src/lib.rs (hunk 5 above)
Comment (lovesegfault) [reply src/lib.rs]: A boundless `Grid` is there because our choice of a HashMap effectively allows for an infinite grid to be used. Right now it's not supported, but since the data types do support it I think we should move into making infinite worlds a possibility.

Comment (lovesegfault) [reply src/lib.rs]: Here I'm not sure whether to establish that every `Grid` from strings is boundless, and then add a function to establish bounds; or to infer a boundary and add a function to remove them. Thoughts?

File: src/lib.rs (hunk 8 above)
Comment (lovesegfault) [reply src/lib.rs:131]: Implementing `From<&str>` causes the compiler to force you to use lifetimes, which I do not yet understand. I tried doing that at first, but I failed, which is why I reverted to String and wrote the `ovec!` macro. If you can figure out how to use lifetimes the change will be appreciated.

File: src/lib.rs (hunk 9 above)
Comment (lovesegfault) [reply src/lib.rs]: This is true, and I argued about this with Daniel the other day about whether or not we should change some of our return types to `Result` (take the `x_bound()` function for example), he disagreed on some instances, so I feel like we should move this into it's own issue to discuss where we should and shouldn't use `Result`

File: src/lib.rs (hunk 7 above)
Comment (lovesegfault) [reply src/lib.rs]: This is true. It also seems like it will require the use of lifetimes. I'm going to study it now and try and fix the other issue that also needs it.

File: src/lib.rs (hunk 8 above)
Comment (lovesegfault) [reply src/lib.rs:131]: I managed to get it working :)

File: src/lib.rs (hunk 5 above)
Comment (maffoo) [reply src/lib.rs]: The cell x- and y-coordinates are `usize`, so definitely not infinite (and you don't lose anything by making the `Grid` bounds required `usize`).

Comment (lovesegfault) [reply src/lib.rs]: I'm opening an issue to discuss this further :)
